name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 2 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ 3 The workflow is now ready to test your code on the runner."
      - name: git log in the repository
        run: |
          git log --oneline -3
      - name: which git
        run: |
          which git 
      - name: List commit in the repository
        run: |
          git ls-files
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
