name: Hello, World!
on: 
  workflow_dispatch 
    inputs:
      username:
        description: 'ykominami'
        required: true
      reason:
        description: 'Why are you running this workflow manually?'
        required: true
        default: 'I am running tests before implementing an autometed workflow'

jobs:
  build:
    name: Greeting2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World! 2"
